### ISSUE TITLE
Support environment variable substitution in RTSP URLs

### ISSUE THREAD

**Issue by robotrapta** [groundlight/framegrab#30]
Framegrab configs will often include an RTSP url, which includes the password in clear-text.  This encourages a bad practice of including secrets (passwords) in the configuration, which often gets managed in git.

e.g.
```
  cameras:
    - name: front-door
      input_type: rtsp
      id:
        rtsp_url: rtsp://admin:secret-password-here@10.92.168.0.95:554
```       
 
Instead, we should support a simple environment-variable substitution syntax like:

```
      id:
        rtsp_url: rtsp://admin:{{RTSP_PASSWORD}}@10.92.168.0.95:554
```       
 
Allowing people to manage the secrets separately from the configuration files.  Environment variables are a common place to manage secrets.  So in RTSP url's we should just look for `{{varname}}` and translate that directly to `os.environ['varname']`
